apiVersion: v1
kind: Namespace
metadata:
  name: openemotion
  labels:
    name: openemotion
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: openemotion-staging
  labels:
    name: openemotion-staging
    environment: staging