#!/usr/bin/env python3
# Wrapper script for probe_cli
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from probe_cli import main
if __name__ == '__main__':
    sys.exit(main())
